export const GET_LOGO_DETAILTAB = 'GET_LOGO_DETAILTAB'
export const GET_CODE_CINEMA_DETAILTAB = 'GET_CODE_CINEMA_DETAILTAB'
export const GET_CODE_GROUP_CINEMA_DETAILTAB = 'GET_CODE_GROUP_CINEMA_DETAILTAB'