export const GET_LOGO_DETAILTAB = 'GET_LOGO_DETAILTAB'
export const GET_MOVIE_DETAIL = "GET_MOVIE_DETAIL";
export const GET_LICH_CHIEU_MOVIE_DETAIL = "GET_LICH_CHIEU_MOVIE_DETAIL";
export const SET_LICH_CHIEU_MOVIE_DETAIL = "SET_LICH_CHIEU_MOVIE_DETAIL";
// chưa sd
export const GET_DATE_MOVIE_DETAIL = "GET_DATE_MOVIE_DETAIL";